### ISSUE TITLE
tappedout is not respecting the legal cards list

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#638]
Reported here: http://tappedout.net/mtg-forum/tappedout/penny-dreadful-format-legal-cards-list-is-incorrect/

**Comment by stash86** [comment]
I don't know how they did their legality thing, but seems like we won't get it fixed anytime soon. The admin said 5 days ago that it should be fixed, but it's not.

**Comment by bakert** [comment]
I have got the best results posting on yeaGO's page:

    http://tappedout.net/users/yeago/

But my last message didn't get a reply. 

The threads I started have mostly just got misinformation:

    http://tappedout.net/mtg-forum/tappedout/penny-dreadful-format-legal-cards-list-is-incorrect/
    http://tappedout.net/mtg-forum/tappedout/penny-dreadful-legality-has-changed-new-legal-cards-list/

Maybe someone else wants to try posting on yeaGO's page.

**Comment by bakert** [comment]
Still broken. I think I'll wait until after the supplemental rotation to try again to get them to update.

<img width="1070" alt="captura de pantalla 2017-05-06 a las 10 03 39 am" src="https://cloud.githubusercontent.com/assets/1541/25774431/5396adb4-3243-11e7-8f04-5bbb273bd09a.png">

**Comment by bakert** [comment]
Posted here - http://tappedout.net/users/yeago/#c3057104

**Comment by stash86** [comment]
Update : tappedout list still broken

http://tappedout.net/mtg-decks/pd-s4-mbc-vampires-1/

**Comment by bakert** [comment]
Told yeaGO here: http://tappedout.net/users/yeago/#c3058898

**Comment by bakert** [comment]
No response. I'll wait a bit and bother them again I guess.

**Comment by bakert** [comment]
Bothered again on yeaGO's wall.

**Comment by bakert** [comment]
Someone mentioned it in Discord so I posted on yeaGO's wall.

http://tappedout.net/users/yeago/#c3193402

I guess Tapped Out is kind of abandonware on some level.

**Comment by stash86** [comment]
And I assume you haven’t get any job offer from them 😁

**Comment by stash86** [comment]
![screenshot-2017-11-13 mtg deck pd s6 demonic](https://user-images.githubusercontent.com/13656154/32705870-fd4c5ad0-c85b-11e7-8677-a91df8c1cde0.png)

Fixed for now

**Comment by bakert** [comment]
I think you have to look on the right-hand side and click the show illegal cards button to see the bug:

![captura de pantalla 2017-11-13 a las 10 56 18 am](https://user-images.githubusercontent.com/1541/32743455-4cd93d16-c861-11e7-8efe-59a23eb3c6a0.png)
![captura de pantalla 2017-11-13 a las 10 56 13 am](https://user-images.githubusercontent.com/1541/32743456-4cf27dee-c861-11e7-8b42-0330da3b4b4c.png)


Did you do that?

**Comment by bakert** [comment]
Trying another way – http://tappedout.net/mtg-forum/tappedout/list-of-bugs-and-feature-requests/?page=7#c3203562

**Comment by bakert** [comment]
Trying another other way – http://tappedout.net/mtg-forum/tappedout/penny-dreadful-legality-malfunctioning/

**Comment by bakert** [comment]
Once more unto the breach … https://tappedout.net/users/yeago/#c3212587

**Comment by bakert** [comment]
<img width="564" alt="captura de pantalla 2017-12-13 a las 2 25 19 p m" src="https://user-images.githubusercontent.com/1541/33965635-7f62f796-e011-11e7-871e-c33a93f30979.png">

HOPE SPRINGS ETERNAL!

**Comment by bakert** [comment]
<img width="364" alt="captura de pantalla 2017-12-14 a las 7 41 50 a m" src="https://user-images.githubusercontent.com/1541/34000515-5b5f1fc8-e0a2-11e7-99a1-142de6f32b4d.png">

**Comment by bakert** [comment]
Woooooop.

**Comment by silasary** [comment]
Wow
